<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FamiliaSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('familia')->insert([
            ['apellido_familia' => 'CASTELLANOS AGUILAR', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'DOMÍNGUEZ AGUILAR', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'FUENTES MATUS', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MALPICA DORANTES', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MARTÍNEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'SANGABRIEL', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'PÉREZ MARTÍNEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'BARRIOS VILLARREAL', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'AGUILAR', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'CAMACHO RAMOS', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GAMBOA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'TOLEDO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GONZALEZ MUÑOA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'PÉREZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ZAMORA ESCOBAR', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ALEGRIA ZAPATA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ARGUELLO CALDERON', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'CABALLERO SOSA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'FLORES', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GALVEZ ESCOBAR', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GUZMAN CASTELLANOS', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GUZMAN SOBRINO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'JIMENEZ SOTO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'NAJERA LESCIEUR', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'PEREZ SANCHEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'RIOS HILERIO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'RODRIGUEZ NUCAMENDI', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'AKIBA AKIBA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ROBLES', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'CASARRUBIAS BALTAZAR', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'CRUZ LOPEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'FERNANDEZ Orantes', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'LOPEZ RAMIREZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ORANTES GARCIA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'OSORIO JIMÉNEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'OVILLA MACIAS', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'RUIZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'SÁNCHEZ VELEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'SANTELIZ OVANDO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'CAMPOS REYES', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ESPINOSA DE LA TORRE', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'FLORES HERNANDEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GARCÍA PASCACIO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GÓMEZ MARTÍNEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GORDILLO CORTES', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GUILLEN ESPINOSA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ALFARO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'LOPEZ CASTILLEJOS', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MACÍAS CISNEROS', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MADRID SUAREZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
        ]);

        DB::table('familia')->insert([
            ['apellido_familia' => 'RAMIREZ CRUZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'SANCHEZ MAURICIO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MOLINA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'VAZQUEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ZENTENO NUCAMENDI', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'AGUILAR GOMEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'AQUINO RUIZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'BRINGAS ZARATE', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'CASTILLEJOS PEREZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'LOPEZ GONZALEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'CUEVAS MENDOZA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GUTIERREZ CASTELLANOS', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MENDEZ DIAZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MERCADO CUETO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'CARDENAS ZUÑIGA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MIGUEL AGUILAR', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'CASTELLANOS', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'PADILLA GARCIA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'PANIAGUA RODRIGUEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'PERALTA RUIZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'RUIZ DOMINGUEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'SALINAS MARINA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'SOLIS SANCHEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'DAMAS VAZQUEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'DE LOS SANTOS DOMÍNGUEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ESPONDA DE NUÑEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GARCIA RODRIGUEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GONZALEZ LARA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'HERNÁNDEZ MINA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'JIMENEZ PEÑALOZA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'LOPEZ HERNANDEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MELGAR GARCIA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MUÑOZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'PASCACIO LOPEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'PEREZ CRUZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'RUIZ SILIAS', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'SALAS ZUARTH', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'SANCHEZ GARCIA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'VILLALOBOS', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ZEBADUA SOLIS', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ACEVES RICO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'LAZARO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'CANTORAL SOLÍS', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'CASTRO LUGO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'COUTIÑO SALDAÑA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'DÍAZ LIEVANO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MADRID MORALES', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MENA NARCIA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MOLINA FRANCO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'LOPEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
        ]);

        DB::table('familia')->insert([
            ['apellido_familia' => 'OJEDA ALIAS', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'RAMIREZ SERRANO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'RAMOS ROBLES', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'RODAS GONZALEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'TREJO ROJAS', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'URTUZUASTEGUI LEÓN', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'VAZQUEZ DOMINGUEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ARAIZA FLORES', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'BORRAZ ZENTENO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'SOLIS', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ESTRELLA AMORES', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GASQUE GUILLEN', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MELGAR', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'HERNANDEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MADRID LOPEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'NAVA DURAN', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MORENO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'NANGUELU', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'POLA FERNANDEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'Resendiz', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'TOLEDO DÍAZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'CITALAN', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ESCOBAR', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'BERMUDEZ ABADIA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'BORRAZ ROBLES', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'CORZO SOLÍS', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GALVEZ ESPINOSA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GARCÍA TAMAYO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'LOPEZ HERNÁNDEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MORALES GOMEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'OLIVEROS HERNANDEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ROBLES BORREGO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'SOTELO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'TREVIÑO GARCIA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'VAZQUEZ RAMIREZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'VILLEGAS', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'VILLALOBOS FIGUEROA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ALCANTARA MONTERO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'BRINGAS', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'DIAZ NUCAMENDI', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ESCANDÓN FLORES', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GARCÍA FLORES', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GUTIERREZ VELA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MONTERO CAMARGO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'PEREZ GUZMAN', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'VELASCO CRUZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'VILLATORO LLANES', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ZEPEDA AGUILAR', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'TORRES', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'DOMINGUEZ PERIANZA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
        ]);

        DB::table('familia')->insert([
            ['apellido_familia' => 'EDGAR AQUINO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GAMBOA ESCOBAR', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GUADALUPE', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'SANCHEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MALDONADO VAZQUEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MENDOZA RODRIGUEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MORALES HERNÁNDEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MORALES MOLINA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'PAZ ESCOBAR', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'RAMOS URBINA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ROBLES AQUINO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'SALGADO UROSTEGUI', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'SANCHEZ CORDOVA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'TRUJILLO CITALAN', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ZAMORANO VALDESPINO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'Castillejos', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GONZALEZ ESPINOSA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'AZPE', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MONTES', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'Estudillo', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'RODRÍGUEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'RODRIGUEZ SOLANO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MAURICIO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'SOHLE', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'CARRASCO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'TREJO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'FRANCO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GARCIA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'CABALLERO VAZQUEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'CASTILLEJOS SANCHEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'CLEMENTE YAÑEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ESPINOSA GARCIA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GORDILLO FRANCO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GRIMALDO HERNANDEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'HERNANDEZ RAMIREZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MARTÍNEZ AREVALO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'CASTRO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'TOALA RAMIREZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'VIZCAYA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'VELAZQUEZ ANGEL', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'DIAZ ZUÑIGA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'DIAZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ESTRADA YAÑEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GALICIA LOPEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MORALES GARCIA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ROBLERO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'SANDOVAL BROCA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'CAL Y MAYOR RAMOS', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'CASILLAS DURÁN', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ESCOBAR HERNÁNDEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
        ]);

        DB::table('familia')->insert([
            ['apellido_familia' => 'LUGO AVENDAÑO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'Matias', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MOGUEL PÉREZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GONZALEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'OJEDA GORDILLO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'RIVERA LARA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'DOMÍNGUEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'SÁNCHEZ MORENO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ZEBADUA MONZÓN', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ESPINOSA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'CORTES', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'SORDO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GALLEGOS', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GOMEZ LAGUNA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MORALES CUESTA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'POZO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ABREGON CORZO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ALTUZAR HIDALGO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'TOVILLA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'CONSTANTINO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'VICTORIA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MATO MORENO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MORENO ALARCON', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'MORALES', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'SANGEADO', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'CASTELLANOS NANGULLASMU', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'CASTELLANOS RAMOS', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'Orantes', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'Sanchez', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'PARRA', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'Roblero Flores', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'RAMOS', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'REYES', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'ESTRADA VAZQUEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'GALLEGOS SANCHEZ', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'Escobar', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'DURAN', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'Martínez', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
            ['apellido_familia' => 'Orduña Morales', 'observaciones' => null, 'activo' => true, 'creado_at' => now()],
        ]);
    }
}
