<?php

namespace Database\Seeders;

use App\Models\Grupo;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InscripcionSeeder extends Seeder
{
    public function run(): void
    {
        // Mapa nombre_grupo => grupo_id (ciclo 2025-2026, id=2)
        $grupoId = Grupo::all()->pluck('id', 'nombre');

        DB::table('inscripcion')->insert([
            ['alumno_id' => 1, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Conejos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 2, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Conejos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 3, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Conejos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 4, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Conejos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 5, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Conejos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 6, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Conejos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 7, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Gatos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 8, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Gatos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 9, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Gatos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 10, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Gatos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 11, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Gatos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 12, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Gatos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 13, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Gatos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 14, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Gatos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 15, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Gatos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 16, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Gatos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 17, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pandas'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 18, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pandas'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 19, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pandas'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 20, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pandas'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 21, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pandas'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 22, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pandas'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 23, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pandas'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 24, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pandas'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 25, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pandas'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 26, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pandas'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 27, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pandas'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 28, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pandas'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 29, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pandas'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 30, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pingüinos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 31, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pingüinos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 32, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pingüinos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 33, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pingüinos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 34, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pingüinos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 35, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pingüinos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 36, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pingüinos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 37, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pingüinos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 38, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pingüinos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 39, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pingüinos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 40, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pingüinos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 41, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pingüinos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 42, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pingüinos'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 43, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Elefantes'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 44, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Elefantes'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 45, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Elefantes'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 46, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Elefantes'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 47, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Elefantes'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 48, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Elefantes'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 49, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Elefantes'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 50, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Elefantes'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
        ]);

        DB::table('inscripcion')->insert([
            ['alumno_id' => 51, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Elefantes'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 52, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Elefantes'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 53, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Elefantes'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 54, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Elefantes'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 55, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Elefantes'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 56, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Elefantes'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 57, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Elefantes'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 58, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Elefantes'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 59, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Elefantes'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 60, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Elefantes'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 61, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Jaguares'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 62, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Jaguares'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 63, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Jaguares'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 64, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Jaguares'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 65, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Jaguares'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 66, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Jaguares'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 67, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Jaguares'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 68, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Jaguares'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 69, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Jaguares'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 70, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Jaguares'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 71, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Jaguares'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 72, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Jaguares'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 73, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Jaguares'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 74, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Jaguares'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 75, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Jaguares'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 76, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Jaguares'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 77, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Jaguares'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 78, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Jaguares'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 79, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 80, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 81, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 82, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 83, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 84, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 85, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 86, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 87, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 88, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 89, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 90, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 91, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 92, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 93, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 94, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 95, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 96, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Halcones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 97, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Halcones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 98, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Halcones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 99, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Halcones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 100, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Halcones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
        ]);

        DB::table('inscripcion')->insert([
            ['alumno_id' => 101, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Halcones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 102, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Halcones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 103, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Halcones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 104, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Halcones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 105, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Halcones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 106, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Halcones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 107, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Halcones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 108, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Halcones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 109, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Halcones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 110, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Halcones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 111, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Halcones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 112, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Halcones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 113, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Halcones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 114, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Halcones'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 115, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Doraemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 116, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Doraemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 117, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Doraemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 118, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Doraemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 119, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Doraemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 120, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Doraemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 121, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Doraemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 122, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Doraemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 123, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Doraemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 124, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Doraemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 125, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Doraemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 126, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Doraemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 127, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Doraemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 128, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Doraemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 129, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Doraemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 130, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Doraemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 131, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Doraemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 132, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Doraemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 133, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Hamtaro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 134, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Hamtaro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 135, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Hamtaro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 136, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Hamtaro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 137, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Hamtaro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 138, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Hamtaro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 139, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Hamtaro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 140, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Hamtaro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 141, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Hamtaro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 142, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Hamtaro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 143, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Hamtaro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 144, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Hamtaro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 145, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Hamtaro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 146, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Hamtaro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 147, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Hamtaro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 148, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Hamtaro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 149, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Hamtaro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 150, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Hamtaro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
        ]);

        DB::table('inscripcion')->insert([
            ['alumno_id' => 151, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Hamtaro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 152, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Kiki'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 153, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Kiki'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 154, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Kiki'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 155, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Kiki'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 156, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Kiki'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 157, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Kiki'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 158, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Kiki'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 159, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Kiki'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 160, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Kiki'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 161, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Kiki'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 162, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Kiki'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 163, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Kiki'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 164, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Kiki'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 165, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Kiki'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 166, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Kiki'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 167, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Kiki'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 168, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Totoro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 169, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Totoro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 170, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Totoro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 171, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Totoro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 172, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Totoro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 173, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Totoro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 174, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Totoro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 175, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Totoro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 176, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Totoro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 177, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Totoro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 178, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Totoro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 179, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Totoro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 180, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Totoro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 181, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Totoro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 182, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Totoro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 183, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Totoro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 184, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Totoro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 185, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Totoro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 186, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Totoro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 187, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Totoro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 188, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Totoro'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 189, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pokemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 190, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pokemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 191, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pokemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 192, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pokemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 193, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pokemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 194, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pokemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 195, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pokemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 196, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pokemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 197, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pokemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 198, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pokemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 199, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pokemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 200, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pokemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
        ]);

        DB::table('inscripcion')->insert([
            ['alumno_id' => 201, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pokemon'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 202, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Yokai'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 203, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Yokai'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 204, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Yokai'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 205, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Yokai'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 206, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Yokai'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 207, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Yokai'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 208, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Yokai'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 209, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Yokai'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 210, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Yokai'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 211, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Yokai'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 212, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Yokai'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 213, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Yokai'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 214, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Yokai'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 215, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Yokai'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 216, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pacman'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 217, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pacman'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 218, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pacman'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 219, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pacman'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 220, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pacman'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 221, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pacman'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 222, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pacman'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 223, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pacman'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 224, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pacman'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 225, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pacman'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 226, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pacman'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 227, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Pacman'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 228, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Sonic'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 229, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Sonic'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 230, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Sonic'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 231, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Sonic'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 232, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Sonic'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 233, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Sonic'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 234, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Sonic'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 235, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Sonic'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 236, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Sonic'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 237, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Sonic'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 238, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Sonic'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 239, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Sonic'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 240, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Sonic'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 241, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Saint S'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 242, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Saint S'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 243, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Saint S'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 244, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Saint S'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 245, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Saint S'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 246, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Saint S'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 247, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Saint S'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 248, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Saint S'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 249, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Saint S'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 250, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Saint S'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
        ]);

        DB::table('inscripcion')->insert([
            ['alumno_id' => 251, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Saint S'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 252, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Saint S'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 253, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Saint S'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 254, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragon B'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 255, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragon B'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 256, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragon B'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 257, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragon B'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 258, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragon B'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 259, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragon B'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 260, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragon B'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 261, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragon B'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 262, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragon B'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 263, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragon B'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 264, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragon B'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 265, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragon B'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 266, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragon B'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 267, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Dragon B'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 268, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Gundam'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 269, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Gundam'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 270, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Gundam'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 271, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Gundam'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 272, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Gundam'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 273, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Gundam'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 274, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Gundam'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 275, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Gundam'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 276, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Gundam'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 277, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Gundam'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 278, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Gundam'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 279, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Gundam'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 280, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Gundam'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 281, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Shibuya'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 282, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Shibuya'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 283, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Shibuya'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 284, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Shibuya'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 285, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Shibuya'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 286, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Shibuya'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 287, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Shibuya'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 288, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Shibuya'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 289, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Shibuya'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 290, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Shibuya'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 291, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Shibuya'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 292, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Shibuya'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
            ['alumno_id' => 293, 'ciclo_id' => 2, 'grupo_id' => $grupoId['Shibuya'], 'tipo' => 'regular', 'fecha' => '2025-08-25', 'activo' => true],
        ]);
    }
}
